plugins {
    id 'java-library'
}

repositories {
    mavenCentral()
}

tasks.withType(JavaCompile) {
    options.debug = true
}

jar {
    manifest {
        attributes(
                'Premain-Class': 'org.checkerframework.runtime.RuntimeAgent'
                )
    }
}

shadowJar {
    archiveClassifier.set('')
    mergeServiceFiles()
}
